[package]
name = "zaichik"
version = "0.1.0"
authors = ["raventid <juliankul@gmail.com>"]
edition = "2018"

[dependencies]
tokio-util = { version = "0.2", features = ["full"] }
bytes = "0.5"
bincode = "1.3.1"
serde = { version = "1.0", features = ["derive"] }